FROM jenkins/jenkins:lts

USER root

# Installer Docker CLI dans l'image Jenkins
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli

# Donne à l'utilisateur Jenkins l'accès au socket Docker
RUN groupadd -g 984 docker && usermod -aG docker jenkins

USER jenkins

